Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_version = "20171026.1.0"
  config.vm.box_check_update = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.enabled = false
  end

  config.vm.provision "shell", path: "script.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu-export"
    vb.cpus = 1
    vb.memory = 1024
    vb.customize ["modifyvm", :id, "--vram", "16", "--nictype1", "virtio", "--usb", "off", "--uartmode1", "disconnected"]
  end
end
